### ISSUE TITLE
Order 24323 - duplicate order created?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#385] opened 2018-07-14 16:07 UTC
**Summary:**
NOTICE that there are TWO orders #24323 for Steven Humphries
This was found when searching JOBS under an Associate (Bernie Baratta)

**Comment by bartmika** [comment] 2018-07-14 21:28
@rodolfomartinez Hi Rodolfo, I am unable to reproduce, can you please provide detail instructions on how to create this issue?

**Comment by rodolfomartinez** [comment] 2018-07-16 18:59
OK I have some more insights:
Mike Roberts - duplicate work orders happening
24339
24339
24354
24354
24334
24334

Job was unassigned, then re-assigned the same associate (stays as declined) then he gets it again, gets duplicate with the same number but listed for each status. The easiest may be to list only for the last status

**For Job Page (for associate)**:
https://london.workery.ca/en/members/summary/detail/6088/jobs/

**Comment by bartmika** [comment] 2018-07-23 00:00
> Job was unassigned, then re-assigned the same associate (stays as declined) then he gets it again, gets duplicate with the same number but listed for each status. The easiest may be to list only for the last status
I cannot replicate. Please provide more details.

> Mike Roberts - duplicate work orders happening
I cannot replicate. Please provide more details.

@rodolfomartinez @RaymondO55

**Comment by bartmika** [comment] 2018-07-23 00:01
@rodolfomartinez @RaymondO55 Please provide detail steps replicate this issue and please provide the order ID numbers of the bad records you would like for me to delete. Thanks!

**Comment by rodolfomartinez** [comment] 2018-07-24 01:35
@raymondO55 please check

**Comment by bartmika** [comment] 2018-07-24 03:21
@RaymondO55 @rodolfomartinez Any updates on this issue?

**Comment by RaymondO55** [comment] 2018-07-24 16:53
@rodolfomartinez I can't seem to find what the problem is here, have the duplicates resolved itself at some point? I remember seeing the issue with Sue, but there don't seem to be anymore duplicates under the link you've given

**Comment by bartmika** [comment] 2018-07-25 02:05
@rodolfomartinez @RaymondO55 I am going to close this issue because it cannot be replicated anymore - this issue may have already been solved. Please re-open this if the issue comes back.

**Closed by bartmika** 2018-07-25 02:05 UTC
Labels: showstopper
