### ISSUE TITLE
(1) Merge "Skill Required" w/ "Describtion

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#409] opened 2018-07-18 02:42 UTC
For the summary tables (in job pages) which have "Skills required", please merge that row with the description row.

**Comment by rodolfomartinez** [comment] 2018-07-18 02:45
I don't see the benefit here, especially since description could be long or skill sets could be many. Will adjust as enhancement for now, potential wontfix

Thoughts?

**Comment by RaymondO55** [comment] 2018-07-18 16:49
For clarification: 
We do not want the summary table items to be merged. 
What we would like is for the job creation process Step 3 "3. Describe Job" and Step 4 "4. Skills Required" to be merged into one step.

The current workflow is as follows:

1. Search or Add
2. Job Type
3. Describe Job
4. Skills Required
5. Comments
6. Review

The new work flow should be:

1. Search or Add
2. Job Type
3. Skills and Description
4. Comments
5. Review

This change should be combined with the removal of the "Service Fees" field under Step 4 "Skills Required"

**Comment by bartmika** [comment] 2018-07-19 00:52
@RaymondO55 @rodolfomartinez Confirmed! Thank you for the clarification - will implement as specified.

**Comment by bartmika** [comment] 2018-07-19 02:16
@rodolfomartinez Please QA and then close when confirmed.

**Comment by rodolfomartinez** [comment] 2018-07-19 02:56
Confirmed working

**Closed by rodolfomartinez** 2018-07-19 02:56 UTC
Labels: help wanted, question
