### ISSUE TITLE
Service Fees Due Report

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#387] opened 2018-07-14 16:09 UTC
**Summary:**
SERVICE FEES DUE -  the date range is based on what criteria ?  the completion date, the initial start date, the paid date or ?????

**Comment by bartmika** [comment] 2018-07-15 02:19
The current code is...

`jobs = WorkOrder.objects.filter(
        Q(completion_date__isnull=False) &
        Q(invoice_service_fee_amount=0) &
        ~Q(state=WORK_ORDER_STATE.CANCELLED) &
        Q(invoice_service_fee_payment_date__range=(from_dt,to_dt))
    )`

**Comment by rodolfomartinez** [comment] 2018-07-17 20:06
please use the date that it is marked as closed in the system

**Comment by rodolfomartinez** [comment] 2018-07-19 14:42
@bartmika - @SusanFaiarley most recent submissions may supersede this

**Comment by bartmika** [comment] 2018-07-24 01:08
@rodolfomartinez Issue is fixed.

> please use the date that it is marked as closed in the system
The problem lies with the legacy data. To move forward would it be possible for your team to manually update the completion dates to fix the records? I don't want to write an ETL because it might assign incorrect data.

I am closing this issue now.

**Comment by bartmika** [comment] 2018-07-24 01:09
FYI new filter is.

`
jobs = WorkOrder.objects.filter(
        ~Q(associate=None) &
        Q(state=WORK_ORDER_STATE.COMPLETED_BUT_UNPAID)
    ).prefetch_related(
        'customer',
        'associate'
    )
`

**Comment by bartmika** [comment] 2018-07-24 01:13
@RaymondO55 Completed - may you please verify?

**Comment by RaymondO55** [comment] 2018-07-24 17:12
Report seems to be working as intended

**Closed by RaymondO55** 2018-07-24 17:13 UTC
Labels: quality assurance, showstopper
