### ISSUE TITLE
Activity Sheet for a given member giving 500?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#484] opened 2018-08-02 13:47 UTC
**Summary:**
https://london.workery.ca/en/members/summary/detail/6135/activity-sheets/

This URL is giving 500, so far only this member

**Comment by rodolfomartinez** [comment] 2018-08-02 14:59
NoReverseMatch: Reverse for 'workery_tenant_job_retrieve' with arguments '('summary', '')' not found. 1 pattern(s) tried: ['en/jobs\\/(?P<template>[^/]+)\\/detail\\/(?P<pk>[0-9]+)\\/lite\\/$']
(17 additional frame(s) were not displayed)
...
  File "django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "django/urls/resolvers.py", line 636, in _reverse_with_prefix
    raise NoReverseMatch(msg)

**Comment by bartmika** [comment] 2018-08-03 02:07
@rodolfomartinez @RaymondO55 This is a bug caused by #428. This issue is now fixed.

**Closed by bartmika** 2018-08-03 02:07 UTC
Labels: showstopper
