### ISSUE TITLE
Non Manager trying to view a "Completed and Paid" or "Complete and Unpaid"

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#545] opened 2018-09-18 15:54 UTC
**Summary:**
If a non manager clicks view for a job that has "Complete and Paid" or "Complete and Unpaid" the user receives an error 400 (see attached). I believe this is related to #541 

For non managers, could it forward to the regular job summary screen?

**Comment by bartmika** [comment] 2018-09-19 01:31
@rodolfomartinez Hi Rodolfo, bug has been fixed.

Actually the error is not the problem, the error is correct. The problem is that frontline staff should NOT have access to financials, and as a result should NOT have financial completion tasks available to them. I have gone ahead and made frontline staff no longer have access to complete paid/complete unpaid jobs in the tasks list. This issue is now fixed.

**Closed** 2018-09-19 03:32 UTC
Labels: quality assurance
