### ISSUE TITLE
Assigned Jobs button

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#372] opened 2018-07-05 17:33 UTC
**Summary:**
This is not working correctly - it pulls up jobs that are assigned and unassigned

**Comment by bartmika** [comment] 2018-07-07 19:58
@rodolfomartinez Do you have an example of this case?

**Comment by bartmika** [comment] 2018-07-07 22:32
This may have been related to #373 which was fixed. I will close this since I cannot reproduce issue.

**Closed by bartmika** 2018-07-07 22:32 UTC
Labels: showstopper
